BoostryJP/ibet-Network

local-network/Dockerfile, local-network/docker-compose.yml, local-network/run.sh
=> fix: graceful shutdown

local-network/run.sh
=> fix: Fix a bug in the geth startup options

ibet-for-fin-network/README.md, ibet-network/README.md, test-network/README.md
=> Change Network setting procedure

ibet-for-fin-network/validator/run.sh, ibet-network/validator/run.sh, local-network/run.sh, test-network/validator/run.sh
=> Remove allow-insecure-unlock option from validator's startup shell

ibet-for-fin-network/general/run.sh, ibet-for-fin-network/validator/run.sh, ibet-network/general/run.sh, ibet-network/validator/run.sh, local-network/run.sh, test-network/general/run.sh, test-network/validator/run.sh
=> fix: remove unavailable api

ibet-for-fin-network/general/healthcheck.sh, ibet-for-fin-network/general/run.sh, ibet-for-fin-network/validator/healthcheck.sh, ibet-for-fin-network/validator/run.sh, ibet-network/general/healthcheck.sh, ibet-network/general/run.sh, ibet-network/validator/healthcheck.sh, ibet-network/validator/run.sh, local-network/run.sh, test-network/general/healthcheck.sh, test-network/general/run.sh, test-network/validator/healthcheck.sh, test-network/validator/run.sh
=> feat: rename api options

tests/Dockerfile
=> fix: curl in container

ibet-for-fin-network/general/healthcheck.sh, ibet-for-fin-network/general/run.sh, ibet-for-fin-network/validator/healthcheck.sh, ibet-for-fin-network/validator/run.sh, ibet-network/general/healthcheck.sh, ibet-network/general/run.sh, ibet-network/validator/healthcheck.sh, ibet-network/validator/run.sh, local-network/run.sh, test-network/general/healthcheck.sh, test-network/general/run.sh, test-network/validator/healthcheck.sh, test-network/validator/run.sh
=> feat: downgrade quorum

README.md, local-network/README.md
=> feat: add documentation

tests/e2e_test.py, tests/util.py
=> feat: eth_getCode test

README.md, ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/general/Dockerfile, local-network/general/run.sh, local-network/validator/Dockerfile, local-network/validator/run.sh, test-network/general/Dockerfile, test-network/validator/Dockerfile
Upgrade Quorum version to v22.4.4.
=> [Upgrade] Quorum release v22.4.4

ibet-for-fin-network/general/run.sh, ibet-network/general/run.sh, local-network/general/run.sh, test-network/general/run.sh
=> feat: Optional syncmode setting

ibet-network/general/genesis.json_init, ibet-network/validator/genesis.json_init, test-network/general/genesis.json_init, test-network/validator/genesis.json_init
(cherry picked from commit 9cbebf392cee405e8e651de1dc71cfd050ab49b0)
=> fix: Fix QBFTBlock in genesis_init

ibet-for-fin-network/general/healthcheck.sh, ibet-for-fin-network/general/run.sh, ibet-network/general/healthcheck.sh, ibet-network/general/run.sh, local-network/general/healthcheck.sh, local-network/general/run.sh, test-network/general/healthcheck.sh, test-network/general/run.sh
=> feat: Add BLOCK_SYNC_MONITORING_DISABLED option

ibet-for-fin-network/general/healthcheck.sh, ibet-for-fin-network/general/run.sh, ibet-network/general/healthcheck.sh, ibet-network/general/run.sh, local-network/general/healthcheck.sh, local-network/general/run.sh, test-network/general/healthcheck.sh, test-network/general/run.sh
close #117 
cherry-pick from #118
=> feat: Add BLOCK_SYNC_MONITORING_DISABLED option (for v2.1)

ibet-for-fin-network/README.md, ibet-for-fin-network/general/run.sh, ibet-for-fin-network/validator/run.sh, ibet-network/README.md, ibet-network/general/run.sh, ibet-network/validator/run.sh, test-network/README.md, test-network/general/run.sh, test-network/validator/run.sh
Allow identity to be specified as a startup parameter for the geth process.
=> feat: Add identity parameter

ibet-for-fin-network/README.md, ibet-network/README.md, test-network/README.md
=> fix: [Doc] Added nodekey to startup parameter

README.md, README_JA.md
=> feat: Add Japanese README

README.md, README_JA.md, ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile, tests/e2e_test.py
=> feat: Bump Quorum version to v22.7.5

ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile
Fetch the following fix.
- https://github.com/BoostryJP/quorum/pull/12
=> bump quorum to v2.1.0_beta3

ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile
I have already tested on my local network that the Validator/General node works fine.
=> Bump alpine version to 3.17

ibet-for-fin-network/general/run.sh, ibet-for-fin-network/validator/run.sh, ibet-network/general/run.sh, ibet-network/validator/run.sh, local-network/docker-compose.yml, local-network/general/run.sh, local-network/validator/run.sh, test-network/general/run.sh, test-network/validator/run.sh
=> trap SIGTERM

ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile, tests/e2e_testing.md
close #147 , close #148 , close #149
=> Bump Quorum/Golang/alpine

ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/docker-compose.yml, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile
https://github.com/BoostryJP/quorum/releases/tag/v2.2.1
=> Upgrade BoostryJP/quorum to v2.2.1

ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/docker-compose.yml, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile
🤖 https://github.com/BoostryJP/quorum/releases/tag/v2.2.2
=> Upgrade BoostryJP/quorum to v2.2.2

ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/docker-compose.yml, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile
=> Update quorum version to v2.3.0

ibet-for-fin-network/general/run.sh, ibet-for-fin-network/validator/run.sh, ibet-network/general/run.sh, ibet-network/validator/run.sh, local-network/docker-compose.yml, local-network/general/run.sh, local-network/validator/run.sh, test-network/general/run.sh, test-network/validator/run.sh
- Added verbosity option to geth command
- The default value is set to 3 for the local network, and 2 for others.
=> Add verbosity option to geth command

ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile
=> Upgrade golang to v1.23

local-network/docker-compose.yml, local-network/general/run.sh, local-network/validator/run.sh
- Added metrics option to local-network
=> Add metrics option to local-network

local-network/docker-compose.yml, test-network/validator/genesis.json, test-network/validator/genesis.json_init
Since the transition block of testnet was confirmed, I changed the setting value of genesis.json.
=> Set testnet transition block

ibet-for-fin-network/README.md, ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/general/run.sh, ibet-for-fin-network/validator/Dockerfile, ibet-for-fin-network/validator/run.sh, ibet-network/README.md, ibet-network/general/Dockerfile, ibet-network/general/run.sh, ibet-network/validator/Dockerfile, ibet-network/validator/run.sh, local-network/docker-compose.yml, local-network/general/Dockerfile, local-network/general/run.sh, local-network/validator/Dockerfile, local-network/validator/run.sh, test-network/README.md, test-network/general/Dockerfile, test-network/general/run.sh, test-network/validator/Dockerfile, test-network/validator/run.sh, tests/e2e_testing.md
- close #185 
- close #184 
- Upgrade quorum to v2.5.0_beta1
=> Delete unnecessary startup options

ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/docker-compose.yml, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile
=> Upgrade quorum to v2.5.0_beta2

ibet-for-fin-network/general/Dockerfile, ibet-for-fin-network/validator/Dockerfile, ibet-network/general/Dockerfile, ibet-network/validator/Dockerfile, local-network/docker-compose.yml, local-network/general/Dockerfile, local-network/validator/Dockerfile, test-network/general/Dockerfile, test-network/validator/Dockerfile
=> Upgrade quorum to v2.5.0
